### ISSUE TITLE
Enkele feature detects ontbreken nog

### ISSUE THREAD

**Issue by KrijnHoetmer** [dennis-van-bennekom/bt3-supermarkt#2]
Die van `addEventListener`, `querySelector` en `classList` bijvoorbeeld. Je test nu op `draggable`, maar de rest niet. Kan best zijn dat een browser wel `draggable` ondersteunt, maar niet die andere APIs. Zal niet heel vaak voorkomen, maar toch handiger om daar wel op te testen (zie bijvoorbeeld het Cutting the Mustard patroon).

**Comment by dennis-van-bennekom** [comment]
een aantal feature detects toegevoegd.
