### ISSUE TITLE
Gebruik van `rem` in CSS

### ISSUE THREAD

**Issue by KrijnHoetmer** [dennis-van-bennekom/bt3-supermarkt#4]
Pas op met het gebruik van `rem` voor layout, aangezien er nog browsers vrij rondlopen die dit niet ondersteunen.

**Comment by dennis-van-bennekom** [comment]
fallback gemaakt dmv pixels

**Comment by KrijnHoetmer** [comment]
Check! Niet de meest nette oplossing natuurlijk, maar het Web is nou eenmaal smerig :)
